### ISSUE TITLE
some plugins not loading

### ISSUE THREAD

**Issue by Hashfyre** [JAremko/alpine-vim#6]
Contrary to the screenshot in README
this is how my `vim` looks on running
`edit run`
<img width="563" alt="screen shot 2018-02-14 at 4 28 56 am" src="https://user-images.githubusercontent.com/581287/36178707-caacddd4-113f-11e8-8b24-083ca9e0d476.png">

I'm running `Docker version 18.02.0-ce-rc2, build f968a2c` on `macos sierra`

**Comment by JAremko** [comment]
@Hashfyre It uses solarized dark color theme for Vim so your terminal also should be in `solarized dark`

https://github.com/altercation/vim-colors-solarized#important-note-for-terminal-users
